version: '3'
services:
    wp_db:
        image: 'mariadb:10.1'
        volumes:
            - 'db_data:/var/lib/mysql'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    wp:
        depends_on:
            - wp_db
        image: 'wordpress:latest'
        ports:
            - '8000:8000'
        restart: always
        environment:
            WORDPRESS_DB_HOST: 'wp_db:3306'
            WORDPRESS_DB_PASSWORD: wordpress
    pma:
        depends_on:
            - wp_db
        image: phpmyadmin/phpmyadmin
        links:
            - 'wp_db:db'
        ports:
            - '8181:80'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
volumes:
    db_data:
        driver: local
