version: '3'
services:
    web:
        image: khunpleum/node-vote-app:1.0
        container_name: node-app
        ports:
            - '3000:3000'
        depends_on:
            - redis
    redis:
        image: 'redis:3-alpine'
        container_name: redis-database
